### ISSUE TITLE
Incorrect "behind" value

### ISSUE THREAD

**Issue by Nahor** [roblesch/bevy_spatial_boids#1]
```rust
// Don't evaluate boids behind
if angle_towards(t0.translation.xy(), t1.translation.xy()) > BOID_FOV {
    continue;
}
```
https://github.com/roblesch/bevy_spatial_boids/blob/0259b1bf298ee9c4f1a51a7ff1ad9c08370b22f5/src/main.rs#L184C8-L187C10

The code above is incorrect. It measures the *absolute/world-space angle* necessary for one boid to face another (which is why you can use it to make the boid go toward the mouse cursor). But what you want is "behind", i.e. the *relative/object-space angle*, i.e. `<angle toward other boid> - <current boid direction>`.
As-is, anything on the left of the boid is "behind", even if the boid is facing left as well.

This should do what you want:
```rust
if let Some(vec_to_norm) = vec_to.try_normalize() {
    let quat_to = Quat::from_rotation_arc_2d(Vec2::X, vec_to_norm);
    let angle = t0.rotation.angle_between(quat_to);
    if angle > BOID_FOV {
        continue;
    }
}
```

**Comment by roblesch** [comment]
Thank you for taking the time to perform a thorough review and offer a fix!
